"""Initial migration

Revision ID: 356882f2c93e
Revises: 
Create Date: 2024-09-14 13:40:06.936409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356882f2c93e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('followers')
    op.drop_table('event')
    op.drop_table('contact')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('startTime', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('endTime', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('timeCreated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('follower_id', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('event_id', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('comment', sa.String(length=80), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('uni_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.alter_column('uni_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('comment')
        batch_op.drop_column('event_id')
        batch_op.drop_column('follower_id')
        batch_op.drop_column('timeCreated')
        batch_op.drop_column('endTime')
        batch_op.drop_column('startTime')
        batch_op.drop_column('location')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('id')
        batch_op.drop_column('name')

    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=80), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.VARCHAR(length=80), nullable=False),
    sa.Column('location', sa.VARCHAR(length=80), nullable=False),
    sa.Column('startTime', sa.VARCHAR(length=80), nullable=False),
    sa.Column('endTime', sa.VARCHAR(length=80), nullable=False),
    sa.Column('timeCreated', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=80), nullable=False),
    sa.Column('follower_id', sa.VARCHAR(length=80), nullable=False),
    sa.Column('timeCreated', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=80), nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=80), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=80), nullable=False),
    sa.Column('timeCreated', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
